/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatContainer: typeof import('./components/ChatContainer.vue')['default']
    CopyIcon: typeof import('./components/CopyIcon.vue')['default']
    IconCopy: typeof import('./components/IconCopy.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    MessageItem: typeof import('./components/MessageItem.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SideBar: (typeof import('./components/Sidebar.vue'))['default']
    TypingIndicator: typeof import('./components/TypingIndicator.vue')['default']
  }
}
